// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"api/internal/dal/model"
)

func newEmailVerification(db *gorm.DB, opts ...gen.DOOption) emailVerification {
	_emailVerification := emailVerification{}

	_emailVerification.emailVerificationDo.UseDB(db, opts...)
	_emailVerification.emailVerificationDo.UseModel(&model.EmailVerification{})

	tableName := _emailVerification.emailVerificationDo.TableName()
	_emailVerification.ALL = field.NewAsterisk(tableName)
	_emailVerification.ID = field.NewInt32(tableName, "id")
	_emailVerification.Email = field.NewString(tableName, "email")
	_emailVerification.EmailNorm = field.NewString(tableName, "email_norm")
	_emailVerification.Purpose = field.NewString(tableName, "purpose")
	_emailVerification.CodeHash = field.NewBytes(tableName, "code_hash")
	_emailVerification.ExpiresAt = field.NewTime(tableName, "expires_at")
	_emailVerification.ConsumedAt = field.NewTime(tableName, "consumed_at")
	_emailVerification.AttemptCount = field.NewInt32(tableName, "attempt_count")
	_emailVerification.CreatedAt = field.NewTime(tableName, "created_at")
	_emailVerification.RequestIP = field.NewBytes(tableName, "request_ip")
	_emailVerification.UserAgent = field.NewString(tableName, "user_agent")

	_emailVerification.fillFieldMap()

	return _emailVerification
}

type emailVerification struct {
	emailVerificationDo

	ALL          field.Asterisk
	ID           field.Int32
	Email        field.String
	EmailNorm    field.String
	Purpose      field.String
	CodeHash     field.Bytes
	ExpiresAt    field.Time
	ConsumedAt   field.Time
	AttemptCount field.Int32
	CreatedAt    field.Time
	RequestIP    field.Bytes
	UserAgent    field.String

	fieldMap map[string]field.Expr
}

func (e emailVerification) Table(newTableName string) *emailVerification {
	e.emailVerificationDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e emailVerification) As(alias string) *emailVerification {
	e.emailVerificationDo.DO = *(e.emailVerificationDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *emailVerification) updateTableName(table string) *emailVerification {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt32(table, "id")
	e.Email = field.NewString(table, "email")
	e.EmailNorm = field.NewString(table, "email_norm")
	e.Purpose = field.NewString(table, "purpose")
	e.CodeHash = field.NewBytes(table, "code_hash")
	e.ExpiresAt = field.NewTime(table, "expires_at")
	e.ConsumedAt = field.NewTime(table, "consumed_at")
	e.AttemptCount = field.NewInt32(table, "attempt_count")
	e.CreatedAt = field.NewTime(table, "created_at")
	e.RequestIP = field.NewBytes(table, "request_ip")
	e.UserAgent = field.NewString(table, "user_agent")

	e.fillFieldMap()

	return e
}

func (e *emailVerification) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *emailVerification) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 11)
	e.fieldMap["id"] = e.ID
	e.fieldMap["email"] = e.Email
	e.fieldMap["email_norm"] = e.EmailNorm
	e.fieldMap["purpose"] = e.Purpose
	e.fieldMap["code_hash"] = e.CodeHash
	e.fieldMap["expires_at"] = e.ExpiresAt
	e.fieldMap["consumed_at"] = e.ConsumedAt
	e.fieldMap["attempt_count"] = e.AttemptCount
	e.fieldMap["created_at"] = e.CreatedAt
	e.fieldMap["request_ip"] = e.RequestIP
	e.fieldMap["user_agent"] = e.UserAgent
}

func (e emailVerification) clone(db *gorm.DB) emailVerification {
	e.emailVerificationDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e emailVerification) replaceDB(db *gorm.DB) emailVerification {
	e.emailVerificationDo.ReplaceDB(db)
	return e
}

type emailVerificationDo struct{ gen.DO }

type IEmailVerificationDo interface {
	gen.SubQuery
	Debug() IEmailVerificationDo
	WithContext(ctx context.Context) IEmailVerificationDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IEmailVerificationDo
	WriteDB() IEmailVerificationDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IEmailVerificationDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IEmailVerificationDo
	Not(conds ...gen.Condition) IEmailVerificationDo
	Or(conds ...gen.Condition) IEmailVerificationDo
	Select(conds ...field.Expr) IEmailVerificationDo
	Where(conds ...gen.Condition) IEmailVerificationDo
	Order(conds ...field.Expr) IEmailVerificationDo
	Distinct(cols ...field.Expr) IEmailVerificationDo
	Omit(cols ...field.Expr) IEmailVerificationDo
	Join(table schema.Tabler, on ...field.Expr) IEmailVerificationDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IEmailVerificationDo
	RightJoin(table schema.Tabler, on ...field.Expr) IEmailVerificationDo
	Group(cols ...field.Expr) IEmailVerificationDo
	Having(conds ...gen.Condition) IEmailVerificationDo
	Limit(limit int) IEmailVerificationDo
	Offset(offset int) IEmailVerificationDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IEmailVerificationDo
	Unscoped() IEmailVerificationDo
	Create(values ...*model.EmailVerification) error
	CreateInBatches(values []*model.EmailVerification, batchSize int) error
	Save(values ...*model.EmailVerification) error
	First() (*model.EmailVerification, error)
	Take() (*model.EmailVerification, error)
	Last() (*model.EmailVerification, error)
	Find() ([]*model.EmailVerification, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EmailVerification, err error)
	FindInBatches(result *[]*model.EmailVerification, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.EmailVerification) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IEmailVerificationDo
	Assign(attrs ...field.AssignExpr) IEmailVerificationDo
	Joins(fields ...field.RelationField) IEmailVerificationDo
	Preload(fields ...field.RelationField) IEmailVerificationDo
	FirstOrInit() (*model.EmailVerification, error)
	FirstOrCreate() (*model.EmailVerification, error)
	FindByPage(offset int, limit int) (result []*model.EmailVerification, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IEmailVerificationDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e emailVerificationDo) Debug() IEmailVerificationDo {
	return e.withDO(e.DO.Debug())
}

func (e emailVerificationDo) WithContext(ctx context.Context) IEmailVerificationDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e emailVerificationDo) ReadDB() IEmailVerificationDo {
	return e.Clauses(dbresolver.Read)
}

func (e emailVerificationDo) WriteDB() IEmailVerificationDo {
	return e.Clauses(dbresolver.Write)
}

func (e emailVerificationDo) Session(config *gorm.Session) IEmailVerificationDo {
	return e.withDO(e.DO.Session(config))
}

func (e emailVerificationDo) Clauses(conds ...clause.Expression) IEmailVerificationDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e emailVerificationDo) Returning(value interface{}, columns ...string) IEmailVerificationDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e emailVerificationDo) Not(conds ...gen.Condition) IEmailVerificationDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e emailVerificationDo) Or(conds ...gen.Condition) IEmailVerificationDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e emailVerificationDo) Select(conds ...field.Expr) IEmailVerificationDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e emailVerificationDo) Where(conds ...gen.Condition) IEmailVerificationDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e emailVerificationDo) Order(conds ...field.Expr) IEmailVerificationDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e emailVerificationDo) Distinct(cols ...field.Expr) IEmailVerificationDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e emailVerificationDo) Omit(cols ...field.Expr) IEmailVerificationDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e emailVerificationDo) Join(table schema.Tabler, on ...field.Expr) IEmailVerificationDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e emailVerificationDo) LeftJoin(table schema.Tabler, on ...field.Expr) IEmailVerificationDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e emailVerificationDo) RightJoin(table schema.Tabler, on ...field.Expr) IEmailVerificationDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e emailVerificationDo) Group(cols ...field.Expr) IEmailVerificationDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e emailVerificationDo) Having(conds ...gen.Condition) IEmailVerificationDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e emailVerificationDo) Limit(limit int) IEmailVerificationDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e emailVerificationDo) Offset(offset int) IEmailVerificationDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e emailVerificationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IEmailVerificationDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e emailVerificationDo) Unscoped() IEmailVerificationDo {
	return e.withDO(e.DO.Unscoped())
}

func (e emailVerificationDo) Create(values ...*model.EmailVerification) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e emailVerificationDo) CreateInBatches(values []*model.EmailVerification, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e emailVerificationDo) Save(values ...*model.EmailVerification) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e emailVerificationDo) First() (*model.EmailVerification, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmailVerification), nil
	}
}

func (e emailVerificationDo) Take() (*model.EmailVerification, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmailVerification), nil
	}
}

func (e emailVerificationDo) Last() (*model.EmailVerification, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmailVerification), nil
	}
}

func (e emailVerificationDo) Find() ([]*model.EmailVerification, error) {
	result, err := e.DO.Find()
	return result.([]*model.EmailVerification), err
}

func (e emailVerificationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EmailVerification, err error) {
	buf := make([]*model.EmailVerification, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e emailVerificationDo) FindInBatches(result *[]*model.EmailVerification, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e emailVerificationDo) Attrs(attrs ...field.AssignExpr) IEmailVerificationDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e emailVerificationDo) Assign(attrs ...field.AssignExpr) IEmailVerificationDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e emailVerificationDo) Joins(fields ...field.RelationField) IEmailVerificationDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e emailVerificationDo) Preload(fields ...field.RelationField) IEmailVerificationDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e emailVerificationDo) FirstOrInit() (*model.EmailVerification, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmailVerification), nil
	}
}

func (e emailVerificationDo) FirstOrCreate() (*model.EmailVerification, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.EmailVerification), nil
	}
}

func (e emailVerificationDo) FindByPage(offset int, limit int) (result []*model.EmailVerification, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e emailVerificationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e emailVerificationDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e emailVerificationDo) Delete(models ...*model.EmailVerification) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *emailVerificationDo) withDO(do gen.Dao) *emailVerificationDo {
	e.DO = *do.(*gen.DO)
	return e
}
