// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                 = new(Query)
	EmailVerification *emailVerification
	User              *user
	UserIdentity      *userIdentity
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	EmailVerification = &Q.EmailVerification
	User = &Q.User
	UserIdentity = &Q.UserIdentity
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                db,
		EmailVerification: newEmailVerification(db, opts...),
		User:              newUser(db, opts...),
		UserIdentity:      newUserIdentity(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	EmailVerification emailVerification
	User              user
	UserIdentity      userIdentity
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		EmailVerification: q.EmailVerification.clone(db),
		User:              q.User.clone(db),
		UserIdentity:      q.UserIdentity.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		EmailVerification: q.EmailVerification.replaceDB(db),
		User:              q.User.replaceDB(db),
		UserIdentity:      q.UserIdentity.replaceDB(db),
	}
}

type queryCtx struct {
	EmailVerification IEmailVerificationDo
	User              IUserDo
	UserIdentity      IUserIdentityDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		EmailVerification: q.EmailVerification.WithContext(ctx),
		User:              q.User.WithContext(ctx),
		UserIdentity:      q.UserIdentity.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
