// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"api/biz/say_right/dal/model"
)

func newTemplateDetail(db *gorm.DB, opts ...gen.DOOption) templateDetail {
	_templateDetail := templateDetail{}

	_templateDetail.templateDetailDo.UseDB(db, opts...)
	_templateDetail.templateDetailDo.UseModel(&model.TemplateDetail{})

	tableName := _templateDetail.templateDetailDo.TableName()
	_templateDetail.ALL = field.NewAsterisk(tableName)
	_templateDetail.ID = field.NewInt32(tableName, "id")
	_templateDetail.TemplateID = field.NewInt32(tableName, "template_id")
	_templateDetail.Headline = field.NewString(tableName, "headline")
	_templateDetail.Summary = field.NewString(tableName, "summary")
	_templateDetail.ReplySoft = field.NewString(tableName, "reply_soft")
	_templateDetail.ReplyNeutral = field.NewString(tableName, "reply_neutral")
	_templateDetail.ReplyFirm = field.NewString(tableName, "reply_firm")
	_templateDetail.WhenNotToUse = field.NewString(tableName, "when_not_to_use")
	_templateDetail.BestPractices = field.NewString(tableName, "best_practices")
	_templateDetail.CreatedAt = field.NewTime(tableName, "created_at")
	_templateDetail.UpdatedAt = field.NewTime(tableName, "updated_at")

	_templateDetail.fillFieldMap()

	return _templateDetail
}

type templateDetail struct {
	templateDetailDo

	ALL           field.Asterisk
	ID            field.Int32
	TemplateID    field.Int32
	Headline      field.String
	Summary       field.String
	ReplySoft     field.String
	ReplyNeutral  field.String
	ReplyFirm     field.String
	WhenNotToUse  field.String
	BestPractices field.String
	CreatedAt     field.Time
	UpdatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (t templateDetail) Table(newTableName string) *templateDetail {
	t.templateDetailDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t templateDetail) As(alias string) *templateDetail {
	t.templateDetailDo.DO = *(t.templateDetailDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *templateDetail) updateTableName(table string) *templateDetail {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt32(table, "id")
	t.TemplateID = field.NewInt32(table, "template_id")
	t.Headline = field.NewString(table, "headline")
	t.Summary = field.NewString(table, "summary")
	t.ReplySoft = field.NewString(table, "reply_soft")
	t.ReplyNeutral = field.NewString(table, "reply_neutral")
	t.ReplyFirm = field.NewString(table, "reply_firm")
	t.WhenNotToUse = field.NewString(table, "when_not_to_use")
	t.BestPractices = field.NewString(table, "best_practices")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")

	t.fillFieldMap()

	return t
}

func (t *templateDetail) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *templateDetail) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 11)
	t.fieldMap["id"] = t.ID
	t.fieldMap["template_id"] = t.TemplateID
	t.fieldMap["headline"] = t.Headline
	t.fieldMap["summary"] = t.Summary
	t.fieldMap["reply_soft"] = t.ReplySoft
	t.fieldMap["reply_neutral"] = t.ReplyNeutral
	t.fieldMap["reply_firm"] = t.ReplyFirm
	t.fieldMap["when_not_to_use"] = t.WhenNotToUse
	t.fieldMap["best_practices"] = t.BestPractices
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
}

func (t templateDetail) clone(db *gorm.DB) templateDetail {
	t.templateDetailDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t templateDetail) replaceDB(db *gorm.DB) templateDetail {
	t.templateDetailDo.ReplaceDB(db)
	return t
}

type templateDetailDo struct{ gen.DO }

type ITemplateDetailDo interface {
	gen.SubQuery
	Debug() ITemplateDetailDo
	WithContext(ctx context.Context) ITemplateDetailDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITemplateDetailDo
	WriteDB() ITemplateDetailDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITemplateDetailDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITemplateDetailDo
	Not(conds ...gen.Condition) ITemplateDetailDo
	Or(conds ...gen.Condition) ITemplateDetailDo
	Select(conds ...field.Expr) ITemplateDetailDo
	Where(conds ...gen.Condition) ITemplateDetailDo
	Order(conds ...field.Expr) ITemplateDetailDo
	Distinct(cols ...field.Expr) ITemplateDetailDo
	Omit(cols ...field.Expr) ITemplateDetailDo
	Join(table schema.Tabler, on ...field.Expr) ITemplateDetailDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITemplateDetailDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITemplateDetailDo
	Group(cols ...field.Expr) ITemplateDetailDo
	Having(conds ...gen.Condition) ITemplateDetailDo
	Limit(limit int) ITemplateDetailDo
	Offset(offset int) ITemplateDetailDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITemplateDetailDo
	Unscoped() ITemplateDetailDo
	Create(values ...*model.TemplateDetail) error
	CreateInBatches(values []*model.TemplateDetail, batchSize int) error
	Save(values ...*model.TemplateDetail) error
	First() (*model.TemplateDetail, error)
	Take() (*model.TemplateDetail, error)
	Last() (*model.TemplateDetail, error)
	Find() ([]*model.TemplateDetail, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TemplateDetail, err error)
	FindInBatches(result *[]*model.TemplateDetail, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TemplateDetail) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITemplateDetailDo
	Assign(attrs ...field.AssignExpr) ITemplateDetailDo
	Joins(fields ...field.RelationField) ITemplateDetailDo
	Preload(fields ...field.RelationField) ITemplateDetailDo
	FirstOrInit() (*model.TemplateDetail, error)
	FirstOrCreate() (*model.TemplateDetail, error)
	FindByPage(offset int, limit int) (result []*model.TemplateDetail, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITemplateDetailDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t templateDetailDo) Debug() ITemplateDetailDo {
	return t.withDO(t.DO.Debug())
}

func (t templateDetailDo) WithContext(ctx context.Context) ITemplateDetailDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t templateDetailDo) ReadDB() ITemplateDetailDo {
	return t.Clauses(dbresolver.Read)
}

func (t templateDetailDo) WriteDB() ITemplateDetailDo {
	return t.Clauses(dbresolver.Write)
}

func (t templateDetailDo) Session(config *gorm.Session) ITemplateDetailDo {
	return t.withDO(t.DO.Session(config))
}

func (t templateDetailDo) Clauses(conds ...clause.Expression) ITemplateDetailDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t templateDetailDo) Returning(value interface{}, columns ...string) ITemplateDetailDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t templateDetailDo) Not(conds ...gen.Condition) ITemplateDetailDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t templateDetailDo) Or(conds ...gen.Condition) ITemplateDetailDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t templateDetailDo) Select(conds ...field.Expr) ITemplateDetailDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t templateDetailDo) Where(conds ...gen.Condition) ITemplateDetailDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t templateDetailDo) Order(conds ...field.Expr) ITemplateDetailDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t templateDetailDo) Distinct(cols ...field.Expr) ITemplateDetailDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t templateDetailDo) Omit(cols ...field.Expr) ITemplateDetailDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t templateDetailDo) Join(table schema.Tabler, on ...field.Expr) ITemplateDetailDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t templateDetailDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITemplateDetailDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t templateDetailDo) RightJoin(table schema.Tabler, on ...field.Expr) ITemplateDetailDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t templateDetailDo) Group(cols ...field.Expr) ITemplateDetailDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t templateDetailDo) Having(conds ...gen.Condition) ITemplateDetailDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t templateDetailDo) Limit(limit int) ITemplateDetailDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t templateDetailDo) Offset(offset int) ITemplateDetailDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t templateDetailDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITemplateDetailDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t templateDetailDo) Unscoped() ITemplateDetailDo {
	return t.withDO(t.DO.Unscoped())
}

func (t templateDetailDo) Create(values ...*model.TemplateDetail) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t templateDetailDo) CreateInBatches(values []*model.TemplateDetail, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t templateDetailDo) Save(values ...*model.TemplateDetail) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t templateDetailDo) First() (*model.TemplateDetail, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TemplateDetail), nil
	}
}

func (t templateDetailDo) Take() (*model.TemplateDetail, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TemplateDetail), nil
	}
}

func (t templateDetailDo) Last() (*model.TemplateDetail, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TemplateDetail), nil
	}
}

func (t templateDetailDo) Find() ([]*model.TemplateDetail, error) {
	result, err := t.DO.Find()
	return result.([]*model.TemplateDetail), err
}

func (t templateDetailDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TemplateDetail, err error) {
	buf := make([]*model.TemplateDetail, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t templateDetailDo) FindInBatches(result *[]*model.TemplateDetail, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t templateDetailDo) Attrs(attrs ...field.AssignExpr) ITemplateDetailDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t templateDetailDo) Assign(attrs ...field.AssignExpr) ITemplateDetailDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t templateDetailDo) Joins(fields ...field.RelationField) ITemplateDetailDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t templateDetailDo) Preload(fields ...field.RelationField) ITemplateDetailDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t templateDetailDo) FirstOrInit() (*model.TemplateDetail, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TemplateDetail), nil
	}
}

func (t templateDetailDo) FirstOrCreate() (*model.TemplateDetail, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TemplateDetail), nil
	}
}

func (t templateDetailDo) FindByPage(offset int, limit int) (result []*model.TemplateDetail, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t templateDetailDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t templateDetailDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t templateDetailDo) Delete(models ...*model.TemplateDetail) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *templateDetailDo) withDO(do gen.Dao) *templateDetailDo {
	t.DO = *do.(*gen.DO)
	return t
}
