// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"api/biz/say_right/dal/model"
)

func newUserIdentity(db *gorm.DB, opts ...gen.DOOption) userIdentity {
	_userIdentity := userIdentity{}

	_userIdentity.userIdentityDo.UseDB(db, opts...)
	_userIdentity.userIdentityDo.UseModel(&model.UserIdentity{})

	tableName := _userIdentity.userIdentityDo.TableName()
	_userIdentity.ALL = field.NewAsterisk(tableName)
	_userIdentity.ID = field.NewInt32(tableName, "id")
	_userIdentity.UserID = field.NewInt32(tableName, "user_id")
	_userIdentity.Provider = field.NewString(tableName, "provider")
	_userIdentity.ProviderSub = field.NewString(tableName, "provider_sub")
	_userIdentity.Email = field.NewString(tableName, "email")
	_userIdentity.EmailNorm = field.NewString(tableName, "email_norm")
	_userIdentity.CreatedAt = field.NewTime(tableName, "created_at")
	_userIdentity.LastLoginAt = field.NewTime(tableName, "last_login_at")

	_userIdentity.fillFieldMap()

	return _userIdentity
}

type userIdentity struct {
	userIdentityDo

	ALL         field.Asterisk
	ID          field.Int32
	UserID      field.Int32
	Provider    field.String
	ProviderSub field.String
	Email       field.String
	EmailNorm   field.String
	CreatedAt   field.Time
	LastLoginAt field.Time

	fieldMap map[string]field.Expr
}

func (u userIdentity) Table(newTableName string) *userIdentity {
	u.userIdentityDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userIdentity) As(alias string) *userIdentity {
	u.userIdentityDo.DO = *(u.userIdentityDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userIdentity) updateTableName(table string) *userIdentity {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewInt32(table, "id")
	u.UserID = field.NewInt32(table, "user_id")
	u.Provider = field.NewString(table, "provider")
	u.ProviderSub = field.NewString(table, "provider_sub")
	u.Email = field.NewString(table, "email")
	u.EmailNorm = field.NewString(table, "email_norm")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.LastLoginAt = field.NewTime(table, "last_login_at")

	u.fillFieldMap()

	return u
}

func (u *userIdentity) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userIdentity) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 8)
	u.fieldMap["id"] = u.ID
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["provider"] = u.Provider
	u.fieldMap["provider_sub"] = u.ProviderSub
	u.fieldMap["email"] = u.Email
	u.fieldMap["email_norm"] = u.EmailNorm
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["last_login_at"] = u.LastLoginAt
}

func (u userIdentity) clone(db *gorm.DB) userIdentity {
	u.userIdentityDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userIdentity) replaceDB(db *gorm.DB) userIdentity {
	u.userIdentityDo.ReplaceDB(db)
	return u
}

type userIdentityDo struct{ gen.DO }

type IUserIdentityDo interface {
	gen.SubQuery
	Debug() IUserIdentityDo
	WithContext(ctx context.Context) IUserIdentityDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserIdentityDo
	WriteDB() IUserIdentityDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserIdentityDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserIdentityDo
	Not(conds ...gen.Condition) IUserIdentityDo
	Or(conds ...gen.Condition) IUserIdentityDo
	Select(conds ...field.Expr) IUserIdentityDo
	Where(conds ...gen.Condition) IUserIdentityDo
	Order(conds ...field.Expr) IUserIdentityDo
	Distinct(cols ...field.Expr) IUserIdentityDo
	Omit(cols ...field.Expr) IUserIdentityDo
	Join(table schema.Tabler, on ...field.Expr) IUserIdentityDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserIdentityDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserIdentityDo
	Group(cols ...field.Expr) IUserIdentityDo
	Having(conds ...gen.Condition) IUserIdentityDo
	Limit(limit int) IUserIdentityDo
	Offset(offset int) IUserIdentityDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserIdentityDo
	Unscoped() IUserIdentityDo
	Create(values ...*model.UserIdentity) error
	CreateInBatches(values []*model.UserIdentity, batchSize int) error
	Save(values ...*model.UserIdentity) error
	First() (*model.UserIdentity, error)
	Take() (*model.UserIdentity, error)
	Last() (*model.UserIdentity, error)
	Find() ([]*model.UserIdentity, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserIdentity, err error)
	FindInBatches(result *[]*model.UserIdentity, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.UserIdentity) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserIdentityDo
	Assign(attrs ...field.AssignExpr) IUserIdentityDo
	Joins(fields ...field.RelationField) IUserIdentityDo
	Preload(fields ...field.RelationField) IUserIdentityDo
	FirstOrInit() (*model.UserIdentity, error)
	FirstOrCreate() (*model.UserIdentity, error)
	FindByPage(offset int, limit int) (result []*model.UserIdentity, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserIdentityDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u userIdentityDo) Debug() IUserIdentityDo {
	return u.withDO(u.DO.Debug())
}

func (u userIdentityDo) WithContext(ctx context.Context) IUserIdentityDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userIdentityDo) ReadDB() IUserIdentityDo {
	return u.Clauses(dbresolver.Read)
}

func (u userIdentityDo) WriteDB() IUserIdentityDo {
	return u.Clauses(dbresolver.Write)
}

func (u userIdentityDo) Session(config *gorm.Session) IUserIdentityDo {
	return u.withDO(u.DO.Session(config))
}

func (u userIdentityDo) Clauses(conds ...clause.Expression) IUserIdentityDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userIdentityDo) Returning(value interface{}, columns ...string) IUserIdentityDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userIdentityDo) Not(conds ...gen.Condition) IUserIdentityDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userIdentityDo) Or(conds ...gen.Condition) IUserIdentityDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userIdentityDo) Select(conds ...field.Expr) IUserIdentityDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userIdentityDo) Where(conds ...gen.Condition) IUserIdentityDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userIdentityDo) Order(conds ...field.Expr) IUserIdentityDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userIdentityDo) Distinct(cols ...field.Expr) IUserIdentityDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userIdentityDo) Omit(cols ...field.Expr) IUserIdentityDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userIdentityDo) Join(table schema.Tabler, on ...field.Expr) IUserIdentityDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userIdentityDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserIdentityDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userIdentityDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserIdentityDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userIdentityDo) Group(cols ...field.Expr) IUserIdentityDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userIdentityDo) Having(conds ...gen.Condition) IUserIdentityDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userIdentityDo) Limit(limit int) IUserIdentityDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userIdentityDo) Offset(offset int) IUserIdentityDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userIdentityDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserIdentityDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userIdentityDo) Unscoped() IUserIdentityDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userIdentityDo) Create(values ...*model.UserIdentity) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userIdentityDo) CreateInBatches(values []*model.UserIdentity, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userIdentityDo) Save(values ...*model.UserIdentity) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userIdentityDo) First() (*model.UserIdentity, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserIdentity), nil
	}
}

func (u userIdentityDo) Take() (*model.UserIdentity, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserIdentity), nil
	}
}

func (u userIdentityDo) Last() (*model.UserIdentity, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserIdentity), nil
	}
}

func (u userIdentityDo) Find() ([]*model.UserIdentity, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserIdentity), err
}

func (u userIdentityDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserIdentity, err error) {
	buf := make([]*model.UserIdentity, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userIdentityDo) FindInBatches(result *[]*model.UserIdentity, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userIdentityDo) Attrs(attrs ...field.AssignExpr) IUserIdentityDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userIdentityDo) Assign(attrs ...field.AssignExpr) IUserIdentityDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userIdentityDo) Joins(fields ...field.RelationField) IUserIdentityDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userIdentityDo) Preload(fields ...field.RelationField) IUserIdentityDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userIdentityDo) FirstOrInit() (*model.UserIdentity, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserIdentity), nil
	}
}

func (u userIdentityDo) FirstOrCreate() (*model.UserIdentity, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserIdentity), nil
	}
}

func (u userIdentityDo) FindByPage(offset int, limit int) (result []*model.UserIdentity, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userIdentityDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userIdentityDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userIdentityDo) Delete(models ...*model.UserIdentity) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userIdentityDo) withDO(do gen.Dao) *userIdentityDo {
	u.DO = *do.(*gen.DO)
	return u
}
