// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserIdentity = "user_identities"

// UserIdentity mapped from table <user_identities>
type UserIdentity struct {
	ID          int32     `gorm:"column:id;primaryKey" json:"id"`
	UserID      int32     `gorm:"column:user_id;not null" json:"user_id"`
	Provider    string    `gorm:"column:provider;not null" json:"provider"`
	ProviderSub string    `gorm:"column:provider_sub" json:"provider_sub"`
	Email       string    `gorm:"column:email" json:"email"`
	EmailNorm   string    `gorm:"column:email_norm" json:"email_norm"`
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	LastLoginAt time.Time `gorm:"column:last_login_at" json:"last_login_at"`
}

// TableName UserIdentity's table name
func (*UserIdentity) TableName() string {
	return TableNameUserIdentity
}
