// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID              int32     `gorm:"column:id;primaryKey" json:"id"`
	Email           string    `gorm:"column:email;not null" json:"email"`
	EmailNorm       string    `gorm:"column:email_norm;not null" json:"email_norm"`
	EmailVerifiedAt time.Time `gorm:"column:email_verified_at" json:"email_verified_at"`
	Status          int32     `gorm:"column:status;not null;default:1" json:"status"`
	CreatedAt       time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
