// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEmailVerification = "email_verifications"

// EmailVerification mapped from table <email_verifications>
type EmailVerification struct {
	ID           int32     `gorm:"column:id;primaryKey" json:"id"`
	Email        string    `gorm:"column:email;not null" json:"email"`
	EmailNorm    string    `gorm:"column:email_norm;not null" json:"email_norm"`
	Purpose      string    `gorm:"column:purpose;not null" json:"purpose"`
	CodeHash     []byte    `gorm:"column:code_hash;not null" json:"code_hash"`
	ExpiresAt    time.Time `gorm:"column:expires_at;not null" json:"expires_at"`
	ConsumedAt   time.Time `gorm:"column:consumed_at" json:"consumed_at"`
	AttemptCount int32     `gorm:"column:attempt_count;not null" json:"attempt_count"`
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	RequestIP    []byte    `gorm:"column:request_ip" json:"request_ip"`
	UserAgent    string    `gorm:"column:user_agent" json:"user_agent"`
}

// TableName EmailVerification's table name
func (*EmailVerification) TableName() string {
	return TableNameEmailVerification
}
