// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTemplate = "templates"

// Template mapped from table <templates>
type Template struct {
	ID          int32     `gorm:"column:id;primaryKey" json:"id"`
	CategoryID  int32     `gorm:"column:category_id;not null" json:"category_id"`
	Title       string    `gorm:"column:title;not null" json:"title"`
	Description string    `gorm:"column:description;not null" json:"description"`
	TagsText    string    `gorm:"column:tags_text;not null" json:"tags_text"`
	IsPro       int32     `gorm:"column:is_pro;not null" json:"is_pro"`
	SortOrder   int32     `gorm:"column:sort_order;not null" json:"sort_order"`
	IsActive    int32     `gorm:"column:is_active;not null;default:1" json:"is_active"`
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Template's table name
func (*Template) TableName() string {
	return TableNameTemplate
}
