// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTemplateDetail = "template_details"

// TemplateDetail mapped from table <template_details>
type TemplateDetail struct {
	ID            int32     `gorm:"column:id;primaryKey" json:"id"`
	TemplateID    int32     `gorm:"column:template_id;not null" json:"template_id"`
	Headline      string    `gorm:"column:headline;not null" json:"headline"`
	Summary       string    `gorm:"column:summary;not null" json:"summary"`
	ReplySoft     string    `gorm:"column:reply_soft;not null" json:"reply_soft"`
	ReplyNeutral  string    `gorm:"column:reply_neutral;not null" json:"reply_neutral"`
	ReplyFirm     string    `gorm:"column:reply_firm;not null" json:"reply_firm"`
	WhenNotToUse  string    `gorm:"column:when_not_to_use;not null" json:"when_not_to_use"`
	BestPractices string    `gorm:"column:best_practices;not null" json:"best_practices"`
	CreatedAt     time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName TemplateDetail's table name
func (*TemplateDetail) TableName() string {
	return TableNameTemplateDetail
}
